version: '3.9'

services:
    lavalink:
        image: fredboat/lavalink:dev
        restart: unless-stopped
        volumes:
            - ./application.yml:/opt/Lavalink/application.
        networks:
            - lavalink
        ports:
            - 2333:2333
            - 8080:8080

networks:
    lavalink: 