version: '3.9'

services:
    lavalink:
        image: fredboat/lavalink:dev
        restart: unless-stopped
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
            - ./plugins/:/opt/Lavalink/plugins/
        networks:
            - lavalink
        ports:
            - 2333:2333

networks:
    lavalink: 